server:
  port: 8082

security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8081/auth/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/auth/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:8081/auth/user/me
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
